name: Daily Ingestion

on:
  schedule:
    - cron: "0 6 * * *"
  # Allow manual triggering too (optional)
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ingestion script
        run: node local.js
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          KEY: ${{ secrets.KEY }}
          GRAFITI_SEARCH: "dappnode"
