name: Recheck validators

on:
  # This will run the workflow every day at 06:00 UTC
  schedule:
    - cron: "0 */4 * * *"
  # Allow manual triggering too (optional)
  workflow_dispatch:

jobs:
  ingest:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ingestion script
        run: node recheck_all_validators.js
        env:
          # The script needs these environment variables:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          KEY: ${{ secrets.KEY }}
